name: Build Ocean Plugin Builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install platform-specific dependencies
        run: sudo apt-get update && sudo apt-get install -y tk8.6 tcl8.6

      - name: Build executable
        run: |
          python build.py

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ocean-${{ matrix.os }}
          path: dist/*
